USE DATABASE FLOW_DB;
USE SCHEMA PUBLIC;
  LIST @ADLS_STAGE;


CREATE OR REPLACE PIPE FLOW_DB.PUBLIC.RAW_PIPE
AS
COPY INTO FLOW_DB.BRONZE.RAW_ORDERS (RAW_DATA, FILE_NAME)
FROM (
    SELECT $1, METADATA$FILENAME
    FROM @FLOW_DB.PUBLIC.ADLS_STAGE
);


COPY INTO FLOW_DB.BRONZE.RAW_ORDERS (RAW_DATA, FILE_NAME)
FROM (
    SELECT $1, METADATA$FILENAME
    FROM @FLOW_DB.PUBLIC.LOCAL_STAGE (FILE_FORMAT => FLOW_DB.PUBLIC.JSON_FORMAT)
);