CREATE OR REPLACE PIPE FLOW_DB.PUBLIC.RAW_PIPE
AS
COPY INTO FLOW_DB.BRONZE.RAW_ORDERS (RAW_DATA, FILE_NAME)
FROM (
    SELECT $1, METADATA$FILENAME
    FROM @FLOW_DB.PUBLIC.ADLS_STAGE
);






SELECT COUNT(*), MIN(LOAD_TS), MAX(LOAD_TS)
FROM FLOW_DB.BRONZE.RAW_ORDERS;




COPY INTO FLOW_DB.BRONZE.RAW_ORDERS (RAW_DATA, FILE_NAME)
FROM (
    SELECT $1, METADATA$FILENAME
    FROM @FLOW_DB.PUBLIC.ADLS_STAGE
);