USE DATABASE FLOW_DB;
USE SCHEMA PUBLIC;


CREATE OR REPLACE STAGE LOCAL_STAGE;




COPY INTO FLOW_DB.BRONZE.RAW_ORDERS (RAW_DATA, FILE_NAME)
FROM (
    SELECT $1, METADATA$FILENAME
    FROM @LOCAL_STAGE
);








CREATE OR REPLACE FILE FORMAT FLOW_DB.PUBLIC.JSON_FORMAT
  TYPE = 'JSON'
  STRIP_OUTER_ARRAY = TRUE;


  COPY INTO FLOW_DB.BRONZE.RAW_ORDERS (RAW_DATA, FILE_NAME)
FROM (
    SELECT $1, METADATA$FILENAME
    FROM @LOCAL_STAGE (FILE_FORMAT => FLOW_DB.PUBLIC.JSON_FORMAT)
);