-- =========================================================
-- 7.3 DEV to PROD Promotion
-- =========================================================

-- 1. Use ACCOUNTADMIN role and create PROD_DB
USE ROLE ACCOUNTADMIN;
CREATE DATABASE IF NOT EXISTS PROD_DB;

-- 2. Clone each schema from development (FLOW_DB) to production (PROD_DB)
CREATE OR REPLACE SCHEMA PROD_DB.BRONZE CLONE FLOW_DB.BRONZE;
CREATE OR REPLACE SCHEMA PROD_DB.PUBLIC CLONE FLOW_DB.PUBLIC;

-- 3. Initialize empty schemas for target production layers if needed
CREATE SCHEMA IF NOT EXISTS PROD_DB.SILVER;
CREATE SCHEMA IF NOT EXISTS PROD_DB.GOLD;
CREATE SCHEMA IF NOT EXISTS PROD_DB.SERVING;

-- 4. Grant schema ownership to SYSADMIN role
GRANT OWNERSHIP ON SCHEMA PROD_DB.BRONZE TO ROLE SYSADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA PROD_DB.PUBLIC TO ROLE SYSADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA PROD_DB.SILVER TO ROLE SYSADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA PROD_DB.GOLD TO ROLE SYSADMIN COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA PROD_DB.SERVING TO ROLE SYSADMIN COPY CURRENT GRANTS;

-- 5. Verify cloned data row counts match dev side-by-side
SELECT 'DEV' AS ENV, 'RAW_ORDERS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM FLOW_DB.PUBLIC.RAW_ORDERS
UNION ALL
SELECT 'PROD' AS ENV, 'RAW_ORDERS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM PROD_DB.PUBLIC.RAW_ORDERS
UNION ALL
SELECT 'DEV' AS ENV, 'STG_ORDERS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM FLOW_DB.PUBLIC.STG_ORDERS
UNION ALL
SELECT 'PROD' AS ENV, 'STG_ORDERS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM PROD_DB.PUBLIC.STG_ORDERS
UNION ALL
SELECT 'DEV' AS ENV, 'AGG_BASE' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM FLOW_DB.PUBLIC.AGG_BASE
UNION ALL
SELECT 'PROD' AS ENV, 'AGG_BASE' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM PROD_DB.PUBLIC.AGG_BASE;

-- 6. Verify Storage Integration ALLOWED_LOCATIONS
DESCRIBE INTEGRATION AZURE_FLOWBRIDGE_INT;
