CREATE DATABASE FLOWBRIDGE_DEV_DB;
CREATE DATABASE FLOWBRIDGE_PROD_DB;


CREATE SCHEMA FLOWBRIDGE_DEV_DB.BRONZE;
CREATE SCHEMA FLOWBRIDGE_DEV_DB.SILVER;
CREATE SCHEMA FLOWBRIDGE_DEV_DB.GOLD;
CREATE SCHEMA FLOWBRIDGE_DEV_DB.SERVING;


CREATE WAREHOUSE FLOW_ETL_WH WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE;
CREATE WAREHOUSE FLOW_BI_WH WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE;


CREATE RESOURCE MONITOR FLOW_ETL_MONITOR WITH CREDIT_QUOTA = 10 TRIGGERS ON 90 PERCENT DO SUSPEND;
CREATE RESOURCE MONITOR FLOW_BI_MONITOR WITH CREDIT_QUOTA = 10 TRIGGERS ON 90 PERCENT DO SUSPEND;