CREATE OR REPLACE STREAM FLOW_DB.SILVER.RAW_ORDERS_STREAM 
ON TABLE FLOW_DB.BRONZE.RAW_ORDERS 
APPEND_ONLY = TRUE;


CREATE OR REPLACE TABLE FLOW_DB.SILVER.STG_ORDERS AS
SELECT 
    RAW_DATA:order_id::STRING AS ORDER_ID,
    RAW_DATA:customer.name::STRING AS CUSTOMER_NAME,
    RAW_DATA:customer.email::STRING AS CUSTOMER_EMAIL,
    RAW_DATA:supplier.company::STRING AS SUPPLIER,
    RAW_DATA:shipment.address::STRING AS SHIP_ADDRESS,
    RAW_DATA:shipment.date::DATE AS SHIP_DATE,
    RAW_DATA:financial.amount::FLOAT AS AMOUNT,
    RAW_DATA:warehouse.location::STRING AS WAREHOUSE,
    FILE_NAME,
    LOAD_TS
FROM FLOW_DB.BRONZE.RAW_ORDERS
WHERE RAW_DATA:order_id IS NOT NULL;


CREATE OR REPLACE TABLE FLOW_DB.SILVER.DEAD_LETTER_ORDERS (
    RAW_DATA VARIANT,
    FILE_NAME STRING,
    LOAD_TS TIMESTAMP_NTZ,
    REASON STRING
);


CREATE OR REPLACE PROCEDURE FLOW_DB.SILVER.SP_LOAD_STG_ORDERS()
RETURNS STRING
LANGUAGE SQL
AS
$$BEGIN
    INSERT INTO FLOW_DB.SILVER.STG_ORDERS
    SELECT 
        RAW_DATA:order_id::STRING,
        RAW_DATA:customer.name::STRING,
        RAW_DATA:customer.email::STRING,
        RAW_DATA:supplier.company::STRING,
        RAW_DATA:shipment.address::STRING,
        RAW_DATA:shipment.date::DATE,
        RAW_DATA:financial.amount::FLOAT,
        RAW_DATA:warehouse.location::STRING,
        FILE_NAME,
        LOAD_TS
    FROM FLOW_DB.SILVER.RAW_ORDERS_STREAM
    WHERE RAW_DATA:order_id IS NOT NULL;


    INSERT INTO FLOW_DB.SILVER.DEAD_LETTER_ORDERS