CREATE OR REPLACE WAREHOUSE FLOW_ETL_WH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE
INITIALLY_SUSPENDED = TRUE;


CREATE OR REPLACE DYNAMIC TABLE FLOW_DB.GOLD.AGG_BASE
LAG = '1 MINUTE'
WAREHOUSE = FLOW_ETL_WH
AS
SELECT 
    f.ORDER_ID,
    c.CUSTOMER_NAME,
    c.CUSTOMER_EMAIL,
    s.SUPPLIER_NAME,
    w.WAREHOUSE_NAME,
    sh.SHIP_ADDRESS,
    sh.SHIP_DATE,
    f.AMOUNT,
    f.LOAD_TS
FROM FLOW_DB.GOLD.FACT_ORDERS f
JOIN FLOW_DB.GOLD.DIM_CUSTOMER c ON f.CUSTOMER_KEY = c.CUSTOMER_KEY
JOIN FLOW_DB.GOLD.DIM_SUPPLIER s ON f.SUPPLIER_KEY = s.SUPPLIER_KEY
JOIN FLOW_DB.GOLD.DIM_WAREHOUSE w ON f.WAREHOUSE_KEY = w.WAREHOUSE_KEY
JOIN FLOW_DB.GOLD.DIM_SHIPMENT sh ON f.SHIPMENT_KEY = sh.SHIPMENT_KEY;




CREATE OR REPLACE DYNAMIC TABLE FLOW_DB.GOLD.DT_ORDER_FULFILLMENT
LAG = '1 MINUTE'
WAREHOUSE = FLOW_ETL_WH
AS
SELECT CUSTOMER_NAME, COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS, SUM(AMOUNT) AS TOTAL_AMOUNT
FROM FLOW_DB.GOLD.AGG_BASE
GROUP BY CUSTOMER_NAME;


CREATE OR REPLACE DYNAMIC TABLE FLOW_DB.GOLD.DT_SUPPLIER_PERFORMANCE
LAG = '1 MINUTE'
WAREHOUSE = FLOW_ETL_WH
AS
SELECT SUPPLIER_NAME, COUNT(DISTINCT ORDER_ID) AS ORDERS_SUPPLIED, SUM(AMOUNT) AS TOTAL_VALUE
FROM FLOW_DB.GOLD.AGG_BASE
GROUP BY SUPPLIER_NAME;


CREATE OR REPLACE DYNAMIC TABLE FLOW_DB.GOLD.DT_INVENTORY_TURNOVER
LAG = '1 MINUTE'
WAREHOUSE = FLOW_ETL_WH
AS
SELECT WAREHOUSE_NAME, COUNT(DISTINCT ORDER_ID) AS ORDERS_PROCESSED, SUM(AMOUNT) AS VALUE_MOVED
FROM FLOW_DB.GOLD.AGG_BASE