USE DATABASE FLOW_DB;
USE SCHEMA PUBLIC;


CREATE OR REPLACE TABLE FLOW_DB.PUBLIC.DIM_CUSTOMER (
    CUSTOMER_KEY INT AUTOINCREMENT,
    CUSTOMER_NAME STRING,
    CUSTOMER_EMAIL STRING,
    PRIMARY KEY (CUSTOMER_KEY)
);


CREATE OR REPLACE TABLE FLOW_DB.PUBLIC.DIM_SUPPLIER (
    SUPPLIER_KEY INT AUTOINCREMENT,
    SUPPLIER_NAME STRING,
    PRIMARY KEY (SUPPLIER_KEY)
);


CREATE OR REPLACE TABLE FLOW_DB.PUBLIC.DIM_WAREHOUSE (
    WAREHOUSE_KEY INT AUTOINCREMENT,
    WAREHOUSE_NAME STRING,
    PRIMARY KEY (WAREHOUSE_KEY)
);


CREATE OR REPLACE TABLE FLOW_DB.PUBLIC.DIM_SHIPMENT (
    SHIPMENT_KEY INT AUTOINCREMENT,
    SHIP_ADDRESS STRING,
    SHIP_DATE DATE,
    PRIMARY KEY (SHIPMENT_KEY)
);


CREATE OR REPLACE TABLE FLOW_DB.PUBLIC.FACT_ORDERS (
    ORDER_ID STRING,
    CUSTOMER_KEY INT,
    SUPPLIER_KEY INT,
    WAREHOUSE_KEY INT,
    SHIPMENT_KEY INT,
    AMOUNT FLOAT,
    FILE_NAME STRING,
    LOAD_TS TIMESTAMP_NTZ,
    PRIMARY KEY (ORDER_ID)
);


CALL FLOW_DB.PUBLIC.SP_LOAD_FACT_ORDERS();
SELECT COUNT(*) FROM FLOW_DB.PUBLIC.FACT_ORDERS;